#!/usr/bin/env python3
"""Plot Fig. 1 (AWGN) and Fig. 2 (Rayleigh) from benchmark CSV outputs.

Each input directory is one model variant generated by
``run_full_channel_benchmark.py``.  The script keeps datasets in small
multiples, so a difficult large-scale dataset cannot visually dominate others.
"""
from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt


BASELINE_LABELS = {"Max Clique": "Max Clique", "ECC": "ECC", "DEMON": "DEMON", "CFinder": "CFinder"}
COLORS = {"SHyRe-count": "#1565c0", "SHyRe-soft-count": "#00897b", "SHyRe-fast-count": "#6a1b9a",
          "Max Clique": "#ef6c00", "ECC": "#2e7d32", "DEMON": "#c62828", "CFinder": "#5d4037"}


def variant_label(directory: Path) -> str:
    name = directory.name.lower()
    if "fast" in name:
        return "SHyRe-fast-count"
    if "soft" in name:
        return "SHyRe-soft-count"
    return "SHyRe-count"


def load(directories: list[Path]):
    values = defaultdict(list)
    for directory in directories:
        with (directory / "snr_baselines.csv").open(encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                if row.get("returncode") != "0":
                    continue
                method = variant_label(directory) if row["method"] == "SHyRe" else BASELINE_LABELS.get(row["method"], row["method"])
                key = (row["dataset"], row["channel"].upper(), int(row["snr_db"]), method)
                values[key].append(float(row["f1"]))
    return {key: sum(items) / len(items) for key, items in values.items()}


def render(values, channel: str, output: Path, figure: int):
    datasets = sorted({key[0] for key in values if key[1] == channel})
    methods = [method for method in COLORS if any(key[1] == channel and key[3] == method for key in values)]
    columns = 3; rows = (len(datasets) + columns - 1) // columns
    fig, axes = plt.subplots(rows, columns, figsize=(4.3 * columns, 3.2 * rows), sharex=True, sharey=True, constrained_layout=True)
    axes = axes.ravel() if hasattr(axes, "ravel") else [axes]
    for ax, dataset in zip(axes, datasets):
        for method in methods:
            points = sorted((key[2], score) for key, score in values.items() if key[:2] == (dataset, channel) and key[3] == method)
            if points:
                ax.plot(*zip(*points), marker="o", ms=3, lw=1.6, label=method, color=COLORS[method])
        ax.set_title(dataset); ax.grid(alpha=.2); ax.set_ylim(-.02, 1.02)
    for ax in axes[len(datasets):]: ax.remove()
    fig.supxlabel("SNR (dB)"); fig.supylabel("Exact-match reconstruction F1")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", ncol=min(4, len(labels)), frameon=False)
    fig.suptitle(f"Fig. {figure}. {channel}: reconstruction across SNR", y=1.04)
    output.mkdir(parents=True, exist_ok=True)
    fig.savefig(output / f"fig_{figure}_{channel.lower()}_snr.png", dpi=220, bbox_inches="tight")
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inputs", type=Path, nargs="+", required=True)
    parser.add_argument("--output", type=Path, default=Path("figures_fig1_2"))
    args = parser.parse_args(); values = load(args.inputs)
    render(values, "AWGN", args.output, 1); render(values, "RAYLEIGH", args.output, 2)


if __name__ == "__main__":
    main()
